on:
  push:
    branches: master

name: Render and Publish

env:
  DEST_ORG: ${{ vars.DEST_ORG }}
  DEST_REPO: ${{ vars.DEST_REPO }}
  PUBLIC_PATH: ${{ vars.PUBLIC_PATH }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up quasar and yarn and build
        run: |
          npm i -g @quasar/cli
          #npm install -g corepack
          #corepack prepare yarn@stable --activate
          npm install
          quasar build
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'dist/spa'
          destination-github-username: ${{ vars.DEST_ORG }}
          destination-repository-name: ${{ vars.DEST_REPO }}
          user-email: surgbc@gmail.com
          target-branch: gh-pages
